#!/usr/bin/env python3
"""
calm-design / scripts/design-md-to-spec.py

DESIGN.md (9-섹션 마크다운) → JSON Spec (json-render 포맷) 변환기.
Phase 1.5 — json-render 점진 채택 결합 #1 구현.

워크플로우:
1. DESIGN.md 9-섹션 파싱
2. validate-design-md.py 통과 검증 (변환 전 게이트)
3. 각 섹션 → JSON Spec 매핑
4. 출력: spec.json (Spec 타입 준수)

사용법:
    python scripts/design-md-to-spec.py \\
        --design examples/01-saas-dashboard-ko/DESIGN.md \\
        --output examples/01-saas-dashboard-ko/spec.json

Exit codes:
    0 — 성공
    1 — 입력 오류
    2 — DESIGN.md 검증 실패 (변환 거부)
"""

import argparse
import json
import re
import sys
import importlib.util
from pathlib import Path


def load_validator():
    """validate-design-md.py 동적 import."""
    spec = importlib.util.spec_from_file_location(
        "validate_design_md", Path(__file__).parent / "validate-design-md.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# ============================================================
# DESIGN.md 섹션 파싱
# ============================================================

def split_sections(content: str) -> dict[int, str]:
    """## 1. ~ ## 9. 헤더 기준 섹션 분리."""
    sections: dict[int, str] = {}
    for num in range(1, 10):
        pattern = rf"^## {num}\.[^\n]*\n(.*?)(?=\n## \d+\.|\Z)"
        match = re.search(pattern, content, re.MULTILINE | re.DOTALL)
        if match:
            sections[num] = match.group(1).strip()
    return sections


def extract_meta_header(content: str) -> dict:
    """파일 상단 '> Generated by calm-design ... LANGUAGE: ko · VARIANCE: 7' 추출."""
    meta = {"language": "ko", "variance": 7, "motion": 6, "density": 4, "mode": "A"}
    m = re.search(r"^> Generated by calm-design.*$", content, re.MULTILINE)
    if not m:
        return meta
    line = m.group(0)
    for k, v_pattern, default in [
        ("language", r"LANGUAGE:\s*(\w+)", "ko"),
        ("variance", r"VARIANCE:\s*(\d+)", 7),
        ("motion", r"MOTION:\s*(\d+)", 6),
        ("density", r"DENSITY:\s*(\d+)", 4),
        ("mode", r"Mode:\s*(\w+)", "A"),
    ]:
        match = re.search(v_pattern, line)
        if match:
            value = match.group(1)
            meta[k] = int(value) if value.isdigit() else value
    return meta


def extract_color_palette(section_2: str) -> dict[str, str]:
    """Section 2의 표에서 (이름, hex) 추출 후 lowercase key dict."""
    colors: dict[str, str] = {}
    for line in section_2.splitlines():
        m = re.match(r"\|\s*([A-Za-z][^|]+?)\s*\|\s*`?(#[0-9a-fA-F]{3,6})`?\s*\|", line)
        if m:
            name, hex_val = m.group(1).strip().lower(), m.group(2)
            # "Canvas" → "canvas", "Off-Black" → "off_black"
            key = re.sub(r"[\s\-]+", "_", name)
            colors[key] = hex_val
    return colors


def extract_typography(section_3: str, language: str) -> dict:
    """Section 3에서 font-family 추출."""
    typo: dict = {"breakKeep": language == "ko"}
    if language == "ko" and "Pretendard" in section_3:
        typo["fontFamily"] = "'Pretendard Variable', Pretendard, system-ui, sans-serif"
    elif "Geist" in section_3:
        typo["fontFamily"] = "Geist, system-ui, sans-serif"
    elif "Cabinet Grotesk" in section_3:
        typo["fontFamily"] = "'Cabinet Grotesk', system-ui, sans-serif"
    return typo


def extract_layout_sections(section_5: str) -> list[str]:
    """Section 5에서 페이지 섹션 순서 추출. 'Hero(Split) → Features(Bento) → ...' 패턴."""
    sections = []
    # 화살표 분리 패턴
    flow_match = re.search(r"([A-Z][\w가-힣]+(?:\([^)]+\))?)\s*→", section_5)
    if flow_match:
        # 모든 → 분리 항목 추출
        flow_line = re.search(r"^.*→.*$", section_5, re.MULTILINE)
        if flow_line:
            parts = re.findall(r"([A-Z][\w가-힣]+)", flow_line.group(0))
            sections = [p for p in parts if len(p) > 2]
    return sections


def derive_page_type(meta: dict, layout_sections: list[str], section_5: str) -> str:
    """
    페이지 타입 추론 — 다중 시그널 가중치 점수.
    각 페이지 타입별 시그널이 가중치 합으로 경쟁. 1위 타입 반환.
    이슈 1 처리: 단순 키워드 매칭 → 가중치 모델로 정밀화.
    """
    text = section_5.lower()
    section_4_text = ""  # caller가 전달하지 않으니 일단 빈 값. 향후 확장 가능.

    # 시그널별 가중치 — 강도가 높을수록 큰 점수
    SIGNALS = {
        "dashboard": [
            ("sidebar", 3), ("topbar", 2), ("top bar", 2),
            ("kpi", 4), ("metric", 2), ("dashboard", 5), ("대시보드", 5),
            ("어드민", 4), ("admin", 3), ("activity", 1), ("chart", 2),
            ("data table", 3), ("관리자", 4),
        ],
        "landing": [
            ("hero", 3), ("footer", 1), ("cta", 2), ("랜딩", 5),
            ("landing", 5), ("social proof", 3), ("testimonial", 2),
            ("pricing", 2), ("features", 1), ("nav", 1),
        ],
        "auth": [
            ("로그인", 5), ("회원가입", 5), ("login", 5), ("sign", 4),
            ("signup", 5), ("auth", 4), ("password", 3), ("otp", 3),
            ("인증", 4), ("forgot", 2),
        ],
        "mobile": [
            ("bottom tab", 5), ("bottom sheet", 4), ("status bar", 3),
            ("floating action", 3), ("fab", 2), ("모바일 앱", 5),
            ("ios", 2), ("android", 2), ("safe area", 3),
            ("h-14", 1),  # 모바일 표준 높이
        ],
        "content": [
            ("article", 3), ("blog", 4), ("아티클", 3), ("블로그", 4),
            ("post", 2), ("editorial", 3), ("max-w-[65ch]", 2),
            ("prose", 3), ("65ch", 2),
        ],
    }

    # 다이얼 보정: DENSITY 8+면 dashboard·content에 +2점
    dial_bonus = {}
    if meta.get("density", 4) >= 7:
        dial_bonus["dashboard"] = 2
        dial_bonus["content"] = 1
    if meta.get("density", 4) <= 3 and meta.get("variance", 7) >= 6:
        dial_bonus["landing"] = 1

    scores = {pt: 0 for pt in SIGNALS}
    for pt, signals in SIGNALS.items():
        for keyword, weight in signals:
            # 단어 경계 매칭 (sidebar가 "considerable" 같은 단어 안에 있어도 X)
            count = text.count(keyword)
            if count > 0:
                scores[pt] += weight * min(count, 3)  # 동일 키워드 반복은 최대 3회만 가중
        scores[pt] += dial_bonus.get(pt, 0)

    # 최고 점수 + 동점일 때 우선순위 (auth > dashboard > mobile > content > landing)
    if max(scores.values()) == 0:
        return "landing"  # 시그널 0이면 기본
    priority = ["auth", "dashboard", "mobile", "content", "landing"]
    best = max(scores, key=lambda pt: (scores[pt], -priority.index(pt)))
    return best


# ============================================================
# JSON Spec 생성
# ============================================================

def build_spec(content: str) -> dict:
    """DESIGN.md 텍스트를 받아 json-render Spec 객체로 반환."""
    meta = extract_meta_header(content)
    sections = split_sections(content)
    if 1 not in sections or 5 not in sections:
        raise ValueError("DESIGN.md에 Section 1·5가 필수. 9-섹션 표준 준수 확인 필요.")

    colors = extract_color_palette(sections.get(2, ""))
    typography = extract_typography(sections.get(3, ""), meta["language"])
    layout_sections = extract_layout_sections(sections.get(5, ""))
    page_type = derive_page_type(meta, layout_sections, sections.get(5, ""))

    # Spec 골격
    elements: dict = {}

    # 페이지 타입별 root + children 구성
    if page_type == "dashboard":
        elements["dashboard"] = {
            "type": "DashboardLayout",
            "props": {"sidebarWidth": 240},
            "children": ["sidebar", "main"],
        }
        elements["sidebar"] = {"type": "Sidebar", "props": {}, "children": []}
        elements["main"] = {
            "type": "MainArea",
            "props": {},
            "children": ["page-header", "kpi-grid"],
        }
        elements["page-header"] = {
            "type": "PageHeader",
            "props": {"title": "대시보드"},
        }
        elements["kpi-grid"] = {
            "type": "BentoGrid",
            "props": {"columns": 4, "gap": 16},
            "children": [],
        }
        root_key = "dashboard"
    elif page_type == "landing":
        elements["landing"] = {
            "type": "Stack",
            "props": {"direction": "vertical"},
            "children": ["nav", "hero", "features", "cta", "footer"],
        }
        elements["nav"] = {"type": "Navigation", "props": {}}
        elements["hero"] = {"type": "HeroSection", "props": {"title": ""}}
        elements["features"] = {"type": "BentoGrid", "props": {"columns": 3}, "children": []}
        elements["cta"] = {"type": "CTABanner", "props": {}}
        elements["footer"] = {"type": "Footer", "props": {}}
        root_key = "landing"
    elif page_type == "mobile":
        elements["mobile"] = {
            "type": "MobileLayout",
            "props": {"maxWidth": 480},
            "children": ["topbar", "content", "tabbar"],
        }
        elements["topbar"] = {"type": "MobileTopBar", "props": {}}
        elements["content"] = {"type": "ScrollArea", "props": {}, "children": []}
        elements["tabbar"] = {"type": "BottomTabBar", "props": {}}
        root_key = "mobile"
    else:  # auth
        elements["auth"] = {
            "type": "AuthCard",
            "props": {"title": "로그인"},
            "children": ["email-input", "password-input", "submit"],
        }
        elements["email-input"] = {
            "type": "TossInput",
            "props": {"label": "이메일", "type": "email"},
        }
        elements["password-input"] = {
            "type": "TossInput",
            "props": {"label": "비밀번호", "type": "password"},
        }
        elements["submit"] = {
            "type": "TossPrimaryButton",
            "props": {"label": "로그인"},
        }
        root_key = "auth"

    spec = {
        "root": root_key,
        "elements": elements,
        "state": {
            "theme": {
                "atmosphere": sections.get(1, "").split("\n")[0][:200],
                "language": meta["language"],
                "colors": colors,
                "typography": typography,
                "motion": {
                    "ease": [0.16, 1, 0.3, 1],
                    "duration": 0.6,
                    "respectsReducedMotion": True,
                },
                "dials": {
                    "variance": meta["variance"],
                    "motion": meta["motion"],
                    "density": meta["density"],
                },
            },
            "_meta": {
                "generatedBy": "calm-design",
                "designMd": True,
                "mode": meta["mode"],
                "pageType": page_type,
            },
        },
    }
    return spec


def main():
    parser = argparse.ArgumentParser(description="DESIGN.md → JSON Spec 변환")
    parser.add_argument("--design", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--skip-validate", action="store_true",
                        help="validate-design-md.py 사전 검증 스킵")
    args = parser.parse_args()

    md_path = Path(args.design)
    if not md_path.exists():
        print(f"❌ DESIGN.md 없음: {md_path}")
        sys.exit(1)

    content = md_path.read_text(encoding="utf-8")

    if not args.skip_validate:
        validator = load_validator()
        results = validator.validate(content)
        failed = [r for r in results if not r.passed]
        if failed:
            print(f"❌ DESIGN.md 검증 실패 ({len(failed)}개) — 변환 거부")
            for r in failed:
                print(f"   {r.name}: {r.detail}")
            print("\n→ DESIGN.md를 수정한 뒤 재실행하거나 --skip-validate 사용")
            sys.exit(2)
        print(f"✅ DESIGN.md 검증 통과 ({len(results)}개 항목)")

    try:
        spec = build_spec(content)
    except ValueError as e:
        print(f"❌ 변환 실패: {e}")
        sys.exit(2)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(spec, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"\n📦 JSON Spec 생성:")
    print(f"   root: {spec['root']}")
    print(f"   elements: {len(spec['elements'])}개")
    print(f"   colors: {len(spec['state']['theme']['colors'])}개")
    print(f"   pageType: {spec['state']['_meta']['pageType']}")
    print(f"📝 출력: {out_path}")


if __name__ == "__main__":
    main()
