#!/usr/bin/env python3
from __future__ import annotations
"""
calm-design / scripts/multi-variant.py

Mode D — 3개 베리언트의 DESIGN.md + JSON Spec 골격을 동시 생성.
실제 LLM 호출은 Cowork·Claude Code의 인-스킬 Claude가 담당.
이 스크립트는 매트릭스 적용·디렉토리 구성·comparison.md 자동 생성을 담당.

워크플로우:
1. 사용자 입력에서 page_type, language, preservation_contract 파싱
2. 3-베리언트 매트릭스 생성 (V1 미니멀 / V2 트렌디 / V3 도메인 매칭)
3. 보존 조건 적용 (액센트 hex 등 강제 유지)
4. 각 베리언트 디렉토리 + DESIGN.md 골격 작성
5. comparison.md 자동 생성

사용법:
    python scripts/multi-variant.py \\
        --page-type landing \\
        --language ko \\
        --preserve-accent "#3182F6" \\
        --output-dir .calm-design/variants

Exit codes:
    0 — 성공 (3개 베리언트 골격 생성)
    1 — 입력 오류
"""

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path


# ============================================================
# 3-베리언트 매트릭스 (modes/multi-variant.md Step 2와 동기)
# ============================================================

@dataclass(frozen=True)
class VariantSpec:
    code: str
    name: str
    variance: int
    motion: int
    density: int
    base_palette: str
    base_palette_hex: str
    accent_hex: str
    layout_pattern: str
    motion_tone: str
    typography: str
    signature: str
    scenarios: tuple[str, ...]


VARIANT_MATRIX = (
    VariantSpec(
        code="v1-minimal",
        name="미니멀 차분",
        variance=4, motion=4, density=4,
        base_palette="Stone",
        base_palette_hex="#FAFAF9",
        accent_hex="#10B981",  # Calm Emerald
        layout_pattern="Asymmetric Whitespace",
        motion_tone="Hover만 + Fade-up (절제)",
        typography="Pretendard 정통 (한국어 우선)",
        signature="(없음 — 절제 자체가 시그니처)",
        scenarios=("B2B SaaS", "금융·보험", "신뢰 우선 도메인"),
    ),
    VariantSpec(
        code="v2-trendy",
        name="트렌디 다이내믹",
        variance=8, motion=7, density=5,
        base_palette="Zinc",
        base_palette_hex="#FAFAFA",
        accent_hex="#F59E0B",  # Warm Amber
        layout_pattern="Bento Grid + Inline Image Typography",
        motion_tone="Magnetic Button + Counter Up + Stagger",
        typography="Cabinet Grotesk + Pretendard (한·영 페어링)",
        signature="Inline Image Typography (Hero에 1회)",
        scenarios=("마케팅 랜딩", "크리에이터·미디어", "스타트업 D2C"),
    ),
    VariantSpec(
        code="v3-domain",
        name="도메인 매칭",
        variance=7, motion=6, density=4,
        base_palette="Stone-50 + Toss-style",
        base_palette_hex="#FAFAFA",
        accent_hex="#3182F6",  # Toss Blue 기본 (사용자 의도로 변경 가능)
        layout_pattern="Split Hero + Bento Features",
        motion_tone="Stagger Cascade + Spring (표준)",
        typography="Pretendard 표준",
        signature="(도메인에 따라 — 한국 SaaS면 Toss Bottom Sheet)",
        scenarios=("사용자 명시 도메인", "기존 브랜드 가이드 있는 경우"),
    ),
)


def apply_preservation(variants: tuple[VariantSpec, ...], accent: str | None) -> list[VariantSpec]:
    """보존 조건 적용 — 액센트 hex 강제 유지."""
    if not accent:
        return list(variants)
    result = []
    for v in variants:
        # frozen dataclass라 새 인스턴스 생성
        result.append(VariantSpec(
            code=v.code, name=v.name,
            variance=v.variance, motion=v.motion, density=v.density,
            base_palette=v.base_palette, base_palette_hex=v.base_palette_hex,
            accent_hex=accent,  # 강제 교체
            layout_pattern=v.layout_pattern,
            motion_tone=v.motion_tone,
            typography=v.typography,
            signature=v.signature,
            scenarios=v.scenarios,
        ))
    return result


# ============================================================
# DESIGN.md 골격 생성기
# ============================================================

def render_design_md(v: VariantSpec, page_type: str, language: str) -> str:
    """베리언트별 DESIGN.md 골격 (skeleton). 각 섹션은 LLM이 후속 채움.

    이슈 2 처리: 골격은 design-md-spec.md의 9-섹션 구조만 갖춘 상태.
    validate-design-md.py 통과는 LLM 후속 작업(9섹션 ≥ 50자 채우기) 후에만 가능.
    골격 단계에서 직접 변환·검증하면 ❌ 발생 — 의도된 동작.
    """
    lang_typo = "Pretendard" if language == "ko" else "Geist"
    return f"""# Design System: {page_type.capitalize()} — Variant {v.code.upper()} ({v.name})

> Generated by calm-design · LANGUAGE: {language} · VARIANCE: {v.variance} · MOTION: {v.motion} · DENSITY: {v.density} · Mode: D · Variant: {v.code} ({v.name})
> ⚠️ Status: SKELETON — LLM이 9섹션을 채워야 validate-design-md.py 통과 가능

## 1. Visual Theme & Atmosphere

(LLM이 베리언트 톤에 맞춰 채움. 키워드: {v.name}, {v.layout_pattern}, {v.signature})

## 2. Color Palette & Roles

| Canvas | `{v.base_palette_hex}` | 페이지 배경 ({v.base_palette}) |
| Surface | `#FFFFFF` | 카드 배경 |
| Ink | `#0A0A0A` | 본문·헤드라인 |
| Mute | `#71717A` | 보조 텍스트 |
| Border | `#E4E4E7` | 분할선 |
| Accent | `{v.accent_hex}` | CTA, 강조 |

## 3. Typography Rules

{v.typography}.
- Family: `{lang_typo} Variable, {lang_typo}, system-ui, sans-serif`
- 헤드라인: `tracking-tight leading-tight`
- 본문: `leading-relaxed max-w-[65ch]`
{"- 한국어: word-break: keep-all 강제" if language == "ko" else ""}

금지: Inter, font-thin/extralight/light.

## 4. Component Stylings

(LLM이 페이지 타입에 맞는 컴포넌트 6상태 정의)

## 5. Layout Principles

- 패턴: **{v.layout_pattern}**
- min-h-[100dvh] 강제 (h-screen 금지)
- 반응형: 모바일 1-column, 태블릿 2-column, 데스크톱 비대칭

## 6. Depth & Elevation

(LLM이 채움. 가이드: 그림자는 계층 필요 시만, 네온 글로우 금지)

## 7. Motion & Interaction

- 톤: **{v.motion_tone}**
- Spring: cubic-bezier(0.16, 1, 0.3, 1) 또는 framer-motion spring
- Reduced-motion 의무 지원

## 8. Responsive Behavior

(표준 — Pretendard 환경에서 한국어 본문 max-w-[65ch])

## 9. Anti-Patterns (Project-Specific Banned)

(LLM이 베리언트 톤에 맞게 채움)

---

**적합 시나리오**: {", ".join(v.scenarios)}
**시그니처**: {v.signature}
"""


# ============================================================
# comparison.md 자동 생성
# ============================================================

def render_comparison(variants: list[VariantSpec], page_type: str, language: str) -> str:
    rows = "\n".join(
        f"| {col} | {v1} | {v2} | {v3} |"
        for col, v1, v2, v3 in zip(
            ["다이얼 (V/M/D)", "베이스", "액센트", "레이아웃", "모션 톤", "타이포", "시그니처"],
            [
                f"{variants[0].variance}·{variants[0].motion}·{variants[0].density}",
                f"{variants[0].base_palette} ({variants[0].base_palette_hex})",
                variants[0].accent_hex,
                variants[0].layout_pattern,
                variants[0].motion_tone,
                variants[0].typography,
                variants[0].signature,
            ],
            [
                f"{variants[1].variance}·{variants[1].motion}·{variants[1].density}",
                f"{variants[1].base_palette} ({variants[1].base_palette_hex})",
                variants[1].accent_hex,
                variants[1].layout_pattern,
                variants[1].motion_tone,
                variants[1].typography,
                variants[1].signature,
            ],
            [
                f"{variants[2].variance}·{variants[2].motion}·{variants[2].density}",
                f"{variants[2].base_palette} ({variants[2].base_palette_hex})",
                variants[2].accent_hex,
                variants[2].layout_pattern,
                variants[2].motion_tone,
                variants[2].typography,
                variants[2].signature,
            ],
        )
    )

    return f"""# 🎨 calm-design Mode D — 3안 비교

> 페이지 타입: **{page_type}** · 언어: **{language}**

| 차원 | V1 {variants[0].name} | V2 {variants[1].name} | V3 {variants[2].name} |
|---|---|---|---|
{rows}
| 추천 시나리오 | {", ".join(variants[0].scenarios)} | {", ".join(variants[1].scenarios)} | {", ".join(variants[2].scenarios)} |

## 어떤 베리언트를 선택하시겠어요?

각 베리언트의 DESIGN.md + 산출물을 검토 후 다음 중 선택:

1. **V1 채택** — `variants/{variants[0].code}/`
2. **V2 채택** — `variants/{variants[1].code}/`
3. **V3 채택** — `variants/{variants[2].code}/`
4. **혼합 베리언트** — 예: "V1 컬러 + V2 레이아웃"
5. **모두 거부, 새 매트릭스로 재시도**

선택 후 Mode A·B로 자동 전환되어 풀 구현됩니다.
"""


def main():
    parser = argparse.ArgumentParser(description="Mode D 3-베리언트 골격 생성")
    parser.add_argument("--page-type", default="landing",
                        choices=["landing", "dashboard", "auth", "mobile", "content"])
    parser.add_argument("--language", default="ko", choices=["ko", "en", "auto"])
    parser.add_argument("--preserve-accent", default=None,
                        help="보존할 액센트 hex (예: #3182F6)")
    parser.add_argument("--output-dir", default=".calm-design/variants")
    parser.add_argument("--variants", type=int, default=3,
                        choices=[2, 3], help="베리언트 개수 (2 또는 3)")
    parser.add_argument("--quick", action="store_true",
                        help="Quick 모드 — 1개 베리언트만 풀 셀프-크리틱, 나머지는 정적 분석만 (토큰 비용 ↓↓)")
    parser.add_argument("--full-critique-variant", default="v1-minimal",
                        help="--quick 모드에서 풀 검증할 베리언트 (기본 v1-minimal)")
    args = parser.parse_args()

    # 매트릭스 적용 + 보존 조건
    variants = apply_preservation(VARIANT_MATRIX, args.preserve_accent)
    if args.variants == 2:
        variants = variants[:2]

    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    # 각 베리언트 디렉토리·DESIGN.md 골격 생성
    for v in variants:
        v_dir = out / v.code
        v_dir.mkdir(exist_ok=True)
        design_md = render_design_md(v, args.page_type, args.language)
        (v_dir / "DESIGN.md").write_text(design_md, encoding="utf-8")
        print(f"✅ {v.code} ({v.name}) — {v_dir / 'DESIGN.md'}")

    # comparison.md 생성
    comp_md = render_comparison(variants, args.page_type, args.language)
    (out / "comparison.md").write_text(comp_md, encoding="utf-8")
    print(f"\n📋 comparison.md — {out / 'comparison.md'}")

    # 매트릭스 메타 저장 (LLM 후속 작업용)
    matrix_data = {
        "page_type": args.page_type,
        "language": args.language,
        "preserve_accent": args.preserve_accent,
        "quick_mode": args.quick,
        "full_critique_variant": args.full_critique_variant if args.quick else None,
        "variants": [
            {
                "code": v.code, "name": v.name,
                "variance": v.variance, "motion": v.motion, "density": v.density,
                "base_palette": v.base_palette,
                "accent_hex": v.accent_hex,
                "layout_pattern": v.layout_pattern,
                "motion_tone": v.motion_tone,
                "signature": v.signature,
            }
            for v in variants
        ],
    }
    (out / "_matrix.json").write_text(
        json.dumps(matrix_data, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    print(f"\n📦 Mode D 매트릭스: {len(variants)}개 베리언트 골격 생성 완료")
    if args.quick:
        print(f"   ⚡ Quick 모드 활성 — '{args.full_critique_variant}'만 풀 셀프-크리틱")
        print(f"   나머지 베리언트는 정적 분석만 (토큰 비용 약 1/3)")
    print(f"   다음: 각 DESIGN.md를 LLM(스킬 호출자)이 9-섹션 채우기 + 출력 엔진 변환")


if __name__ == "__main__":
    main()
